### ISSUE TITLE
Make the user flow to personalization of blocks more intuitive 

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/experiments#55] opened 2021-01-12 22:32 UTC
We have discussed this before and it feels like a good time to raise this as an issue to tackle at some point. 

The personalization feature of a variant in XB appears only when clicked on the top of the 'personalized content' block. From a user's perspective, it doesn't seem like the most intuitive flow. Ideally, there could be a third tab after 'Block' settings which can be called as say - 'Personalized content'  to set up the personalization of the variant the user is working in. In essence, just like the proposed [output](https://altis.invisionapp.com/console/share/RM1XQM3HQJ/496912872) design of surfacing each XB variant metrics, we may want to have a split out per variant input section in the editor.  

We could also seek a UX designer's help to understand what might make sense for a better user experience. 

## Requirement:
When I am working with different variants in a personalized content block, I want to avoid the confusion of locating the personalization settings of the XB.  

## Acceptance Criteria: 
- [ ] (To be set up in a refinement session)

**Comment by roborourke** [comment] 2021-01-13 18:22
There isn't really room for it after the "Block" settings tab. I think it might be possible to extend the block settings for child blocks with the variant config but it might be confusing to duplicate just part of that UI. We could probably surface a link or button on the child block settings that refocuses the XB itself and shows the XB settings. There's a few ways we could approach this really.

> Just like the proposed output design of surfacing each XB variant metrics, we may want to have a split out per variant input section in the editor.

I think this acceptance criteria isn't specific enough to be useful right now, it could just be moved to the description and we can work on the acceptance criteria when it comes to refinement.

**Comment by PriyaBhatia0210** [comment] 2021-01-14 20:39
From testing: https://github.com/humanmade/product-dev/issues/602

**Comment by rmccue** [comment] 2021-09-28 10:34
Closing this as the issue isn't currently useful, will revisit in the future as part of design audit.

**Closed as completed by rmccue** 2021-09-28 10:34 UTC
Labels: should have
